/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// Claim clients immediately
clientsClaim()

// Clean up old caches
cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Skip waiting to activate new service worker immediately
self.skipWaiting()

/**
 * Push event handler
 * Displays notification when push message is received
 */
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push received:', event)

  let data = {
    title: 'Agile Planner',
    body: 'Hai una nuova notifica',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    data: {},
  }

  // Parse push payload if available
  if (event.data) {
    try {
      const payload = event.data.json()
      data = {
        title: payload.title || data.title,
        body: payload.body || data.body,
        icon: payload.icon || data.icon,
        badge: payload.badge || data.badge,
        data: payload.data || {},
      }
    } catch (error) {
      console.error('[SW] Error parsing push data:', error)
      // Use text as body if JSON parsing fails
      data.body = event.data.text()
    }
  }

  // Show notification
  const promiseChain = self.registration.showNotification(data.title, {
    body: data.body,
    icon: data.icon,
    badge: data.badge,
    data: data.data,
    tag: 'agile-planner-notification',
    requireInteraction: false,
  })

  event.waitUntil(promiseChain)
})

/**
 * Notification click handler
 * Opens app when notification is clicked
 */
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[SW] Notification clicked:', event)

  event.notification.close()

  // Get task ID from notification data if available
  const taskId = event.notification.data?.taskId
  const url = taskId ? `/?task=${taskId}` : '/'

  // Open or focus app window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clientList => {
      // Check if app is already open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          return client.focus()
        }
      }

      // Open new window if app not already open
      if (self.clients.openWindow) {
        return self.clients.openWindow(url)
      }
    })
  )
})

/**
 * Message handler (for future use)
 */
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('[SW] Message received:', event.data)

  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
